@startuml
'https://plantuml.com/class-diagram

Pokemon <|-- Celebi
Pokemon <|-- Swinub
Swinub <|-- Piloswine
Piloswine  <|-- Mamoswine
Pokemon <|--  Shellos
Shellos  <|-- Gastradon

Move <|-- StatusMove
Move <|-- DamageMove
DamageMove <|-- SpecialMove
DamageMove <|-- PhysicalMove

PhysicalMove <|-- Discharge
PhysicalMove <|-- Tackle
PhysicalMove <|-- ThunderWave
PhysicalMove <|-- IronDefense

SpecialMove <|-- Facade
SpecialMove <|-- ThunderShock
SpecialMove <|-- Nuzzle
SpecialMove <|-- TailWhip

SpecialMove <|-- FocusBlast
SpecialMove <|-- Thunder
StatusMove <|-- ThunderBolt
PhysicalMove <|-- AerialAce





@enduml